version: "3.8"
services:

# Mongo DB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
#   hostname: mongodb
    volumes:
      - /var/lib/mongodb:/data/db
#      - ./mongod.conf:/etc/mongod.conf
#      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
#      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
#      - ./.docker/mongodb/data/db/:/data/db/
#      - ./.docker/mongodb/data/log/:/var/log/mongodb/
#    env_file:
#      - .env
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27018:27017"
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/:/var/www/
    networks:
      - app-network

# Vocabulary Rails
  web:
    hostname: rails_app
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
#    image: "vocabulary"
    image: "wax2"
    depends_on:
      - mongodb
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
